[package]
name = "dino-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raylib = "3.7.0"
glam = "0.20.2"
bevy_ecs = "0.6.0"

[lib]
name = "dino_engine"